"""
Domain models for the AI Recommendation Engine.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

from ecoaudit.optimization.models import ScenarioResult


class RecommendationStatus(Enum):
    """The status of an evaluated recommendation."""
    SUPPORTED = "supported"
    PARTIALLY_SUPPORTED = "partially_supported"
    INSUFFICIENT_DATA = "insufficient_data"
    REQUIRES_REVIEW = "requires_review"
    REJECTED = "rejected"
    NOT_EVALUATED = "not_evaluated"


@dataclass(frozen=True)
class RecommendationCandidate:
    """A structured proposal generated by the AI before evaluation.
    
    This is the parsed JSON output from the LLM. It is NOT trusted until
    validated by the ScenarioEngine.
    """
    title: str
    target_hotspot: str
    intervention_type: str  # "PercentageReduction", "AbsoluteReduction", "FuelSubstitution"
    target_activity_ids: frozenset[str]
    parameters: dict[str, str]  # String-encoded parameters for the intervention
    rationale: str
    required_data: tuple[str, ...] = ()
    needs_review: bool = False


@dataclass(frozen=True)
class RecommendationEvidence:
    """Traceability links for a recommendation."""
    hotspot_label: str
    target_activity_ids: frozenset[str]
    baseline_result_ids: frozenset[str]


@dataclass(frozen=True)
class Recommendation:
    """A final, evaluated recommendation.
    
    Contains the AI's natural language explanation grounded entirely in
    the deterministic ScenarioResult.
    """
    title: str
    rationale: str
    evidence: RecommendationEvidence
    scenario_result: ScenarioResult | None
    explanation: str
    status: RecommendationStatus
    validation_errors: tuple[str, ...] = ()
